

name: Runner tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  USERNAME: ${{secrets.SD_USER}}
  PASSWORD: ${{secrets.SD_PASSWORD}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout Gir
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: setup browser
        uses: abhi1693/setup-browser@v0.3.4
        with:
          browser: chrome
      - name: Test run
        run: mvn clean test